name: Auto add issue to project

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read
  # repository-projects: write # Chỉ cần thiết cho repository-owned projects.
                              # Với user-owned projects, quyền này không giúp GITHUB_TOKEN mặc định.

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: peter-evans/add-to-project@v3 # <--- THAY ĐỔI Ở ĐÂY TỪ v1 SANG v3
        with:
          project-url: https://github.com/users/Couter07/projects/2
          github-token: ${{ secrets.PROJECT_PAT }}
